### ISSUE TITLE
Windows issue, gcloud ssh doesn't keep the engine running

### ISSUE THREAD

**Issue by iopq** [bsteuber/lizzie-gcloud-setup#4]
After I do `gcloud compute ssh ...` it does load Leela Zero, but it errors out right after loading with `? unknown command` as if the ssh thing gave it an extra character or something

worse, that's when it cuts off, doesn't go further instead of continuing to keep it open

Anyone have any idea how to fix this?

**Comment by iopq** [comment]
I solved it, I ran `gcloud compute ssh ... --dry-run` and it showed me the plink command to run directly

**Comment by bsteuber** [comment]
Wow, that's good to hear - I ran into the same issue when trying to make it work on Win...
Would you be willing to add your windows scripts and do a pull request?

**Comment by iopq** [comment]
Of course. I have a slightly different setup, but I can throw up the scripts I personally use

**Comment by iopq** [comment]
C:\PATHTO\plink.exe -t -i C:\Users\YOURUSERNAME\.ssh\google_compute_engine.ppk YOURUSERNAME@IP ./run-leela-zero.sh

of course, everyone's details are different, but when you do the `--dry-run` it prints what those values are

but `--dry-run` usually uses -T, but I had to change to it -t

**Comment by bsteuber** [comment]
Ah, so the trick is avoiding gcloud in the scripts. Thanks, I will try it
and update the repo when I find the time.
