### ISSUE TITLE
error while creating instance

### ISSUE THREAD

**Issue by leobattin** [bsteuber/lizzie-gcloud-setup#6]
while running ./scripts/create-instance.sh I get the following error : 
```
ERROR: (gcloud.compute.instances.create) Could not fetch resource:
 - The resource 'projects/leela-zero-271719/zones/europe-west2-c/acceleratorTypes/nvidia-tesla-v100' was not found
```
I checked twice and am pretty sure followed every step described in README.md. I created a project, enabled compute engine api (this step is missing in README i think), asked for quota of 1 in europe-west-2, got it granted, installed and configured gcloud on my machine, edited config.sh and ran create-instance.sh. Any clue what I am missing ?

**Comment by zapaz** [comment]
2 potential reasons : 
- on the command line you are not connected with same gcloud user (so no access to this ressource)
or
- no v100 hardware available when you ask  , so I would suggest another region : asia-east1-c

**Comment by leobattin** [comment]
Got it working 👍
I missed two steps :
- The quota GPUS_ALL_REGIONS needs to be set at 1 (or more) as well. Not specified in README.md, maybe it would be interesting to add it ?
- Sneaky thing : Google's page about which type of GPU is available in whiche region is quite ambiguous. To avoid any confusion, just type `gcloud compute accelerator-types list` into the console.
That done it worked great, besides some trouble with Lizzie shutting down or getting stuck at 'Leela Zero loading' at startup (happens quite often).
Thank you for your work
